### ISSUE TITLE
Issue: "eslint-plugin-jsdoc" dependency is incompatible with last "LTS Node v20.9.0"

### ISSUE THREAD

**Issue by v-korotkov** [thoughtspot/visual-embed-sdk#1022]
Hi! About a month ago I faced an issue during `yarn install` and it is still present. I am using `@thoughtspot/visual-embed-sdk@^1.23.2`.

`error eslint-plugin-jsdoc@40.3.0: The engine "node" is incompatible with this module. Expected version "^14 || ^16 || ^17 || ^18 || ^19". Got "20.9.0"
`

`error Found incompatible module.
`

The `Node LTS` version was updated from `v18.17.1` to `v20.9.0` and I started to have this issue with your module.
I found, that you still use dependency to `eslint-plugin-jsdoc "^40.1.0"` in the latest version of the module and it is incompatible with `Node LTS  v20.9.0`.

Also, I found, that on the latest version of `eslint-plugin-jsdoc` on `Nov 10, v46.9.0` this problem already has been fixed. Moreover, It has been fixed earlier starting from `Apr 18, v43.0.4`.
[eslint-plugin-jsdoc v43.0.3...v43.0.4](https://github.com/gajus/eslint-plugin-jsdoc/compare/v43.0.3...v43.0.4)

The final version for `Node` was applied on `Apr 24, v43.0.8`
[eslint-plugin-jsdoc v43.0.7...v43.0.8](https://github.com/gajus/eslint-plugin-jsdoc/compare/v43.0.7...v43.0.8)

I request you to release a new version of your module with `eslint-plugin-jsdoc` dependency version `v43.0.8` or more to fix the issue with compatibility with the latest `Node LTS v20.9.0`.

**Comment by ashubham** [comment]
@v-korotkov thanks for reporting, we will update the dependencies and post soon.

**Comment by v-korotkov** [comment]
@ashubham Thank you!

**Comment by ashubham** [comment]
Fixed with 1.26.1
