### ISSUE TITLE
Curly brace is added at the end of tooltip text 

### ISSUE THREAD

**Issue by jemcik** [thoughtspot/visual-embed-sdk#1113]
You can see this bug on your own codesandbox demo page:
https://codesandbox.io/p/sandbox/big-tse-react-demo-i4g9xi?file=%2Fsrc%2Fcomponents%2Fliveboard%2Fliveboard.tsx

There is a label for X-axis and a sorting arrow to the right from label,
hovering over this arrow triggers tooltip being displayed 
which has a curly brace in the end which I believe is added by mistake.

<img width="844" alt="Screenshot 2024-04-26 at 12 57 12" src="https://github.com/thoughtspot/visual-embed-sdk/assets/4085099/3d0b3bff-056d-4181-9ad5-225255931984">

**Comment by ashubham** [comment]
Fixed now, thanks for reporting.
