### ISSUE TITLE
esbuild minification issue

### ISSUE THREAD

**Issue by mdoyle-fleetio** [thoughtspot/visual-embed-sdk#1202]
Hello! 

We are using esbuild as our bundler and I'm encountering an error with SDK version 1.32.1. Whenever we deploy this code I receive the following console error and the SDK fails to load
<img width="2540" alt="Screenshot 2024-08-22 at 1 52 48 PM" src="https://github.com/user-attachments/assets/97291442-0aff-4a66-bd0a-9525ed959465">

Clicking to investigate the source shows this:

<img width="857" alt="Screenshot 2024-08-22 at 1 52 54 PM" src="https://github.com/user-attachments/assets/2a121f87-5029-47d3-8dc6-c9775f081e29">

Here are our relevant package versions
```
"esbuild": "^0.20.2",
"@thoughtspot/visual-embed-sdk": "^1.32.1"
```

I'm able to replicate the minification issue locally because during regular development the sdk works fine but if I set `minify: true` in our esbuild configuration during development - I receive the same error as noted above.

**Comment by ashubham** [comment]
Hi @mdoyle-fleetio 

Are you using Vite along with esbuild? I was able to create a bundle using Vite + esbuild 0.21.5.

Can you share more details of the build setup ? And if it is possible to create a minimal repro on stackblitz/replit

**Comment by mdoyle-fleetio** [comment]
@ashubham we are not using vite at this time. I will try to recreate a minimal app and post the link here.

**Comment by mdoyle-fleetio** [comment]
@ashubham I've narrowed it down to the following line in our esbuild configuration
`target: ["safari12", "edge83", "chrome77", "firefox77", "ios13"]`

specifically the safari12 target. I'm going to work with our frontend team to see if we can adjust this.
