### ISSUE TITLE
Validate Pinboard ID

### ISSUE THREAD

**Issue by UberDoodles** [thoughtspot/visual-embed-sdk#449]
I had an issue today which ended up being due to the pinboard ID not being configured in our application. However, it took a while to track down the issue to it's root cause partly because the SDK didn't identify that the pinboard ID was null; it just tried to use the pinboard ID and ended up with an incorrect URI :

![image](https://user-images.githubusercontent.com/34574335/142008771-7de40836-9090-484e-8427-9c58a44d4fcc.png)

Obviously, this is a weakness in our app as well, which needs to be resolved, but I think it also makes sense for the SDK to validate the pinboard ID in some way before attempting to use it.

**Comment by ashubham** [comment]
Thank you @UberDoodles for the feedback. We will fix this soon.

**Comment by aditya-kumar44** [comment]
The check has been placed for pinboard and visualization. There is no requirement for any check in Search as it works fine without answerId and same for full app since it loads fine without pageId.

**Comment by akashmohapatra** [comment]
This is fixed in the SDK as of the recent alpha versions. Should be available in the upcoming minor release
