### ISSUE TITLE
sdk not compiling due to a TypeScript type error

### ISSUE THREAD

**Issue by mustran** [thoughtspot/visual-embed-sdk#577]
Bug file location: /@thoughtspot/visual-embed-sdk/lib / src / react / util.d.ts
Version: "@thoughtspot/visual-embed-sdk": "^1.9.2"
Environment: Locally

Evidence:

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/45851256/160000443-67571f8e-962a-4273-9c80-30cf31b3735f.png">

**Comment by ashubham** [comment]
@mustran whats the error message you get ? Also whats you typescript version ?

**Comment by mustran** [comment]
@ashubham my TypeScript version is 3.8.3 and the error is: 
```
TypeScript error in .../node_modules/@thoughtspot/visual-embed-sdk/lib/src/react/util.d.ts(4,37):
']' expected.  TS1005
```

**Comment by ashubham** [comment]
So seems this feature is introduced in Typescript 4.1: https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#key-remapping-in-mapped-types

In anycase, you should be using `skipLibCheck: true` in your typescript config, to not typecheck the `.d.ts` files. This should resolve the issue for you on your current typescript version.
