### ISSUE TITLE
Alert messages in the my application are blocking my interface

### ISSUE THREAD

**Issue by gorets** [thoughtspot/visual-embed-sdk#920]
Please remove any alert() from your code because its are blocking my application interface.

Sometimes I can see alert message
`alert(DUPLICATE_TOKEN_ERR);`

I don't know why this happens, but it blocks the interface of my application and it causes inconvenience to the user.

**Comment by yuanyuanliu358** [comment]
Hi @gorets thanks for letting us know. We will check on the issue you reported. 

This alert created to make sure authToken are different than previous one. For the authentication, if it is called with an older token then it will not succeed. 

Hope the explaination helps. 

If you still think it's a bug, can you specify what's the error scenario: Does it happen when everything works fine and authentication is successful? What's the sdk version? Can you provide har file if you think it's a bug? 

Thanks!
Looking forward to hear from you!

**Comment by gorets** [comment]
<img width="1508" alt="Collaboration 2023-07-02 10-17-45" src="https://github.com/thoughtspot/visual-embed-sdk/assets/419682/47e5d41b-d615-44bb-9708-81ea52e7d059">

This happened after an overnight sleep on my laptop with an analytics browser open.

@thoughtspot/visual-embed-sdk "version": "1.20.2"

![image](https://github.com/thoughtspot/visual-embed-sdk/assets/419682/f635a589-ad73-472e-ae58-629e0049d2ba)

**Comment by sergeymanson** [comment]
+

**Comment by sergeymanson** [comment]
any updates?

**Comment by ashubham** [comment]
@sergeymanson To get quicker responses  on questions, please join our developer [discord](https://discord.com/invite/JHPGwCkvjQ)

**Comment by ashubham** [comment]
https://github.com/thoughtspot/visual-embed-sdk/pull/1023 this should solve the issue.

**Comment by ashubham** [comment]
This is now released with 1.26.2. We have a new option called `suppressErrorAlerts` in the `init` to silence all alerts.
