### ISSUE TITLE
Can't remove runtime filters

### ISSUE THREAD

**Issue by timbarclay** [thoughtspot/visual-embed-sdk#924]
I'm trying to implement a page where a user can select a value from a dropdown, and in response it will trigger an `UpdateRuntimeFilters` action to update a filter on a liveboard.

For instance in response to someone clicking "Africa" in a region dropdown, it would run

```typescript
liveboardEmbed.trigger(HostEvent.UpdateRuntimeFilters, [
  {
    columnName: 'Region',
    operator: RuntimeFilterOp.EQ,
    values: ['africa']
  }
]);
```

However, if the user deselects that value, I want to be able to remove that runtime filter. I've tried to do that by passing in an empty list, e.g

```typescript
liveboardEmbed.trigger(HostEvent.UpdateRuntimeFilters, [])
```

but that doesn't have any effect on the embedded liveboard.

Is it possible to remove runtime filters?

**Comment by Nirmay15** [comment]
Hi @timbarclay , can you try using 
```
liveboardEmbed.trigger(HostEvent.UpdateRuntimeFilters, [
  {
    columnName: 'Region',
    operator: RuntimeFilterOp.EQ,
    values: ['africa']
  }
]);
```
For now we don't have direct way to reset whole set of runtime filters but you can reset each columns like this.

**Comment by timbarclay** [comment]
@Nirmay15 Do you mean to unset a filter I should trigger the event again with the same filter that I want to remove? If so that doesn't seem to work either.

If I do 

```
liveboardEmbed.trigger(HostEvent.UpdateRuntimeFilters, [
  {
    columnName: 'Region',
    operator: RuntimeFilterOp.EQ,
    values: ['africa']
  }
]);
```

that adds the filter. Then if I do

```
liveboardEmbed.trigger(HostEvent.UpdateRuntimeFilters, [
  {
    columnName: 'Region',
    operator: RuntimeFilterOp.EQ,
    values: ['africa']
  }
]);
```

again, nothing changes.

**Comment by timbarclay** [comment]
@Nirmay15 Ah, thank you very much, that does work
