### ISSUE TITLE
In Table Answers, three dots still visible even when all actions are hidden

### ISSUE THREAD

**Issue by tshradheya** [thoughtspot/visual-embed-sdk#960]
I am using LiveboardEmbed and set `visibleActions: []`. Yet, in the table for each column I can still see the three dots which do nothing when clicked. Is it possible to hide those?

<img width="172" alt="image" src="https://github.com/thoughtspot/visual-embed-sdk/assets/12574756/e6c9c8df-fe1a-4e8e-aeb5-5a741a1c8ab1">

**Comment by tshradheya** [comment]
Similarly, if all actions are hidden and no liveboard filter exists, I still see this bar on top. not sure if there is any workaround to hide this
<img width="1134" alt="image" src="https://github.com/thoughtspot/visual-embed-sdk/assets/12574756/3f0bb635-b99f-4e1f-82c0-94a361c7f449">

**Comment by ashubham** [comment]
Good point, we will fix this in an upcoming release where we will hide the 3 dot if none of the actions are visible. 

As a workaround you could use a CSS rule to hide these elements https://developers.thoughtspot.com/docs/custom-css#_rules

**Comment by ashubham** [comment]
@tshradheya Also to get quicker responses in the future please join our developer [discord](https://discord.com/invite/JHPGwCkvjQ)

**Comment by tshradheya** [comment]
Perfect, will join the discord. Another quick question is it possible to hide the filters on liveboard and preventing them from being changed?
